### PR TITLE
Utilitary class for function replacement

### PR DESCRIPTION
**Pull request by Shtoyan**
Adds utility code for simple replacement of existing functions' code.

### CODE REVIEW

**Comment by EliotVU** [comment]
Cool, that's a nice way of hooking scripts!

Btw, I think one could modify the VfHash property as well to achieve the same for virtual functions only, also I think it's possible to hook native functions as well by setting NativeIndex to zero and removing the native flag from function flags.

**Comment by Shtoyan** [comment]
Hm, good idea to try.

**Comment by Shtoyan** [comment]
> also I think it's possible to hook native functions as well by setting NativeIndex to zero and removing the native flag from function flags.

You won't believe...

```unrealscript
exec function xxx() {
    local UFunctionCast FunctionCaster;
    local UFunction targetFunc, newFunc;

    FunctionCaster = new class'UFunctionCast';
    targetFunc = FunctionCaster.Cast(function(FindObject("Core.Object.IsOnConsole", class'function')));
    newFunc = FunctionCaster.Cast(function(FindObject("HideMut.HideMutInteraction.IsOnConsoleNew", class'function')));

    warn(">>>>>> newFunc NativeIndex: " $ newFunc.NativeIndex.h $ " / " $ newFunc.NativeIndex.l);   // 0 / 0
    warn(">>>>>> newFunc FunctionFlags: " $ newFunc.FunctionFlags); // 131074

    targetFunc.NativeIndex = newFunc.NativeIndex;
    targetFunc.FunctionFlags = newFunc.FunctionFlags;
    targetFunc.Script = newFunc.Script;

    warn(">>>>>> Testing changed function");
    IsOnConsole();
}

function bool IsOnConsoleNew() {
    warn(">>>>>> AHAHAHAHAHH HOOKED INTO NATIVE!");
    return true;
}
```

And the result is:
```text
Warning: TestInteraction Package.TestInteraction (Function TestMut.TestInteraction.xxx:00F2) >>>>>> newFunc NativeIndex: 0 / 0
Warning: TestInteraction Package.TestInteraction (Function TestMut.TestInteraction.xxx:0126) >>>>>> newFunc FunctionFlags: 131074
Warning: TestInteraction Package.TestInteraction (Function TestMut.TestInteraction.xxx:01A0) >>>>>> Testing changed function
Warning: TestInteraction Package.TestInteraction (Function Core.Object.IsOnConsole:002A) >>>>>> AHAHAHAHAHH HOOKED INTO NATIVE!
```

**Comment by Shtoyan** [comment]
> also I think it's possible to hook native functions as well by setting NativeIndex to zero and removing the native flag from function flags.

You won't believe...

```unrealscript
exec function xxx() {
    local UFunctionCast FunctionCaster;
    local UFunction targetFunc, newFunc;

    FunctionCaster = new class'UFunctionCast';
    targetFunc = FunctionCaster.Cast(function(FindObject("Core.Object.IsOnConsole", class'function')));
    newFunc = FunctionCaster.Cast(function(FindObject("TestMut.TestInteraction.IsOnConsoleNew", class'function')));

    warn(">>>>>> newFunc NativeIndex: " $ newFunc.NativeIndex.h $ " / " $ newFunc.NativeIndex.l);   // 0 / 0
    warn(">>>>>> newFunc FunctionFlags: " $ newFunc.FunctionFlags); // 131074

    targetFunc.NativeIndex = newFunc.NativeIndex;
    targetFunc.FunctionFlags = newFunc.FunctionFlags;
    targetFunc.Script = newFunc.Script;

    warn(">>>>>> Testing changed function");
    IsOnConsole();
}

function bool IsOnConsoleNew() {
    warn(">>>>>> AHAHAHAHAHH HOOKED INTO NATIVE!");
    return true;
}
```

And the result is:
```text
Warning: TestInteraction Package.TestInteraction (Function TestMut.TestInteraction.xxx:00F2) >>>>>> newFunc NativeIndex: 0 / 0
Warning: TestInteraction Package.TestInteraction (Function TestMut.TestInteraction.xxx:0126) >>>>>> newFunc FunctionFlags: 131074
Warning: TestInteraction Package.TestInteraction (Function TestMut.TestInteraction.xxx:01A0) >>>>>> Testing changed function
Warning: TestInteraction Package.TestInteraction (Function Core.Object.IsOnConsole:002A) >>>>>> AHAHAHAHAHH HOOKED INTO NATIVE!
```

**Comment by EliotVU** [comment]
Nice, that could come in handy!

**Pull request merged**
